// Static offline railway station dataset for autocompletion
const MAJOR_STATIONS = [
    { code: "NDLS", name: "New Delhi" },
    { code: "DLI", name: "Old Delhi" },
    { code: "NZM", name: "Hazrat Nizamuddin" },
    { code: "ANVT", name: "Anand Vihar Terminal" },
    { code: "BCT", name: "Mumbai Central" },
    { code: "CSMT", name: "Chhatrapati Shivaji Maharaj Terminus" },
    { code: "BDTS", name: "Bandra Terminus" },
    { code: "LTT", name: "Lokmanya Tilak Terminus" },
    { code: "HWH", name: "Howrah Junction" },
    { code: "SDAH", name: "Sealdah" },
    { code: "KOAA", name: "Kolkata" },
    { code: "MAS", name: "Chennai Central" },
    { code: "MS", name: "Chennai Egmore" },
    { code: "SBC", name: "KSR Bengaluru City" },
    { code: "YPR", name: "Yesvantpur Junction" },
    { code: "HYB", name: "Hyderabad Deccan" },
    { code: "SC", name: "Secunderabad Junction" },
    { code: "PNBE", name: "Patna Junction" },
    { code: "LKO", name: "Lucknow Charbagh" },
    { code: "CNB", name: "Kanpur Central" },
    { code: "BSB", name: "Varanasi Junction" },
    { code: "PRYJ", name: "Prayagraj Junction" },
    { code: "ADI", name: "Ahmedabad Junction" },
    { code: "PUNE", name: "Pune Junction" },
    { code: "JP", name: "Jaipur Junction" },
    { code: "GHY", name: "Guwahati" },
    { code: "BPL", name: "Bhopal Junction" },
    { code: "RKMP", name: "Rani Kamlapati" },
    { code: "NAG", name: "Nagpur Junction" },
    { code: "CHTS", name: "Cochin Harbour Terminus" },
    { code: "ERS", name: "Ernakulam Junction" },
    { code: "TVC", name: "Thiruvananthapuram Central" },
    { code: "CDG", name: "Chandigarh Junction" },
    { code: "ASR", name: "Amritsar Junction" },
    { code: "JAT", name: "Jammu Tawi" },
    { code: "SVDK", name: "Shri Mata Vaishno Devi Katra" },
    { code: "BBS", name: "Bhubaneswar" },
    { code: "R", name: "Raipur Junction" },
    { code: "RNC", name: "Ranchi Junction" },
    { code: "GKP", name: "Gorakhpur Junction" }
];
